### ISSUE TITLE
Issues with creating new users on aem configuration in the author

### ISSUE THREAD

**Issue by Carnifrex** [shinesolutions/puppet-aem-resources#82] opened 2020-03-04 16:28 UTC
When running the AEM curator with the config_author_primary.pp and enabling the reconfiguration we get the following error with the create user step: 

[1;31mError: Could not set 'present' on ensure: Missing end tag for 'td' (got "a")
Line: 19
Position: 520
Last 80 unconsumed characters:
 (file: /vagrant/aempuppet/modules/aem_resources/manifests/create_system_users.pp, line: 31)

**Comment by Carnifrex** [comment] 2020-03-17 12:59
Any idea on how we can avoid this?

**Comment by henrykuijpers** [comment] 2020-03-18 11:08
FYI: This is (one of the possible) outputs from a call to AEM:
{code}
<html>

<head>
	<title>Error while processing /home/users/i/cieA5pW7ChztRCoCdWyd</title>
</head>

<body>
	<h1>Error while processing /home/users/i/cieA5pW7ChztRCoCdWyd</h1>
	<table>
		<tbody>
			<tr>
				<td>Status</td>
				<td>
					<div id="Status">500</div>
				</td>
			</tr>
			<tr>
				<td>Message</td>
				<td>
					<div id="Message">org.apache.sling.api.resource.PersistenceException: Unable to commit changes to
						session.</div>
				</td>
			</tr>
			<tr>
				<td>Location</td>
				<td><img class="cq-LinkChecker cq-LinkChecker--prefix cq-LinkChecker--invalid" src="/libs/cq/linkchecker/resources/linkcheck_o.gif" alt="invalid link: /home/users/i/cieA5pW7ChztRCoCdWyd" title="invalid link: /home/users/i/cieA5pW7ChztRCoCdWyd" border="0">/home/users/i/cieA5pW7ChztRCoCdWyd</a>
				</td>
			</tr>
			<tr>
				<td>Parent Location</td>
				<td><a href="/home/users/i" id="ParentLocation">/home/users/i</a></td>
			</tr>
			<tr>
				<td>Path</td>
				<td>
					<div id="Path">/home/users/i/cieA5pW7ChztRCoCdWyd</div>
				</td>
			</tr>
			<tr>
				<td>Referer</td>
				<td>
					<div id="Referer"></div>
				</td>
			</tr>
			<tr>
				<td>ChangeLog</td>
				<td>
					<div id="ChangeLog"></div>
				</td>
			</tr>
		</tbody>
	</table>
	<p><img class="cq-LinkChecker cq-LinkChecker--prefix cq-LinkChecker--invalid" src="/libs/cq/linkchecker/resources/linkcheck_o.gif" alt="invalid link: /home/users/i/cieA5pW7ChztRCoCdWyd" title="invalid link: /home/users/i/cieA5pW7ChztRCoCdWyd" border="0">Modified Resource</a>
	</p>
	<p><a href="/home/users/i">Parent of Modified Resource</a></p>
</body>

</html>
{code}

Especially notice the link-checker images, that open a <img> tag, then close it with </a>. Causing the Ruby XML parser to go nuts.

**Comment by henrykuijpers** [comment] 2020-03-18 13:35
Ok, traced it down a bit further. The issue is in the call to:
```
http://localhost:4502/home/users/e/pvLioZnclBn_8_8XL8Mq?deleteAuthorizable=
```

The following headers are sent with this call:
```
0 = {HostPortHttpField@23780} "Host: localhost:4502"
1 = {HttpField@23781} "Accept: */*"
2 = {HttpField@23782} "User-Agent: OpenAPI-Generator/3.0.0/ruby"
3 = {HttpField@23783} "Content-Type: multipart/form-data"
4 = {HttpField@23784} "Authorization: Basic YWRtaW46YWRtaW4="
5 = {HttpField@23785} "Content-Length: 0"
```

This does not make sense of course: Sending a content-type of multipart/form-data, without a boundary. This causes AEM (and specifically Sling and then specifically org.apache.commons.fileupload.FileUploadBase) to throw this error, which in turn generates the above HTML response, which in turn cannot be parsed by the Ruby XML parser, since AEM's LinkChecker messes it up. :D 

So, the solution would be to not send the Content-Type header (since the POST request has an empty body and therefore no content type).

**Comment by mbloch1986** [comment] 2020-04-17 08:38
@henrykuijpers  & @Carnifrex are you able to give more context ?

What's the username where this happens ?

Is it possible that user name or the user path does not match the real path in the AEM repository ?

**Comment by henrykuijpers** [comment] 2020-04-17 08:43
No, the issue is that the request is done specifying that the body is multipart. The jetty server in AEM requires that a boundary is present then, which is not.

**Comment by mbloch1986** [comment] 2020-04-18 01:43
Does this happen when you are trying to delete a user or when you create a user ?

**Comment by mbloch1986** [comment] 2020-04-18 04:43
I actually can reproduce your error manually in two different ways ...


**1. when I try to delete a user which doesn't exist using curl**
```
[root@83d1fa4814fa puppet-aem-resources]# curl -X POST -u admin:admin http://localhost:4502/home/users/c/aVJ_O9QbbQbNh4LF5fGS -F deleteAuthorizable='' -vvv
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 127.0.0.1:4502...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 4502 (#0)
* Server auth using Basic with user 'admin'
> POST /home/users/c/aVJ_O9QbbQbNh4LF5fGS HTTP/1.1
> Host: localhost:4502
> Authorization: Basic YWRtaW46YWRtaW4=
> User-Agent: curl/7.66.0
> Accept: */*
> Content-Length: 153
> Content-Type: multipart/form-data; boundary=------------------------e35d54725271acc4
> 
* We are completely uploaded and fine
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Server Error
< Date: Sat, 18 Apr 2020 04:29:35 GMT
< X-Content-Type-Options: nosniff
< X-Frame-Options: SAMEORIGIN
* Added cookie cq-authoring-mode="TOUCH" for domain localhost, path /, expire 1587788975
< Set-Cookie: cq-authoring-mode=TOUCH;Path=/;Expires=Sat, 25-Apr-2020 04:29:35 GMT;Max-Age=604800
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
< Content-Type: text/html;charset=utf-8
< Transfer-Encoding: chunked
< 
<html>
<head>
    <title>Error while processing /home/users/c/aVJ_O9QbbQbNh4LF5fGS</title>
</head>
    <body>
    <h1>Error while processing /home/users/c/aVJ_O9QbbQbNh4LF5fGS</h1>
    <table>
        <tbody>
            <tr>
                <td>Status</td>
                <td><div id="Status">500</div></td>
            </tr>
            <tr>
                <td>Message</td>
                <td><div id="Message">org.apache.sling.api.resource.PersistenceException: Unable to commit changes to session.</div></td>
            </tr>
            <tr>
                <td>Location</td>
                <td><img class="cq-LinkChecker cq-LinkChecker--prefix cq-LinkChecker--invalid" src="/libs/cq/linkchecker/resources/linkcheck_o.gif" alt="invalid link: /home/users/c/aVJ_O9QbbQbNh4LF5fGS" title="invalid link: /home/users/c/aVJ_O9QbbQbNh4LF5fGS" border="0">/home/users/c/aVJ_O9QbbQbNh4LF5fGS<img class="cq-LinkChecker cq-LinkChecker--suffix cq-LinkChecker--invalid" src="/libs/cq/linkchecker/resources/linkcheck_c.gif" border="0"></td>
            </tr>
            <tr>
                <td>Parent Location</td>
                <td><a href="/home/users/c" id="ParentLocation">/home/users/c</a></td>
            </tr>
            <tr>
                <td>Path</td>
                <td><div id="Path">/home/users/c/aVJ_O9QbbQbNh4LF5fGS</div></td>
            </tr>
            <tr>
                <td>Referer</td>
                <td><div id="Referer"></div></td>
            </tr>
            <tr>
                <td>ChangeLog</td>
                <td><div id="ChangeLog"></div></td>
            </tr>
        </tbody>
    </table>
    <p><img class="cq-LinkChecker cq-LinkChecker--prefix cq-LinkChecker--invalid" src="/libs/cq/linkchecker/resources/linkcheck_o.gif" alt="invalid link: /home/users/c/aVJ_O9QbbQbNh4LF5fGS" title="invalid link: /home/users/c/aVJ_O9QbbQbNh4LF5fGS" border="0">Modified Resource<img class="cq-LinkChecker cq-LinkChecker--suffix cq-LinkChecker--invalid" src="/libs/cq/linkchecker/resources/linkcheck_c.gif" border="0"></p>
    <p><a href="/home/users/c">Parent of Modified Resource</a></p>
    </body>
* Connection #0 to host localhost left intact
</html>
```


**2. using puppet-aem-resource:**

This only works if I force a return of false positive for the method `exists` 
https://github.com/shinesolutions/puppet-aem-resources/blob/master/lib/puppet/provider/aem_user/aem.rb#L43-L50

If the `exists` method returns `true` even though the user doesn't exists in AEM, than the deletion method will fail with the error message you described above... Now ihn your case I am assuming that the exists method is returning a false positive ... Can you verify the return state of the method `exists` when you try to delete the user  ? 

The exists method is using the `getNode` operation from swagger-aem
https://github.com/shinesolutions/swagger-aem/blob/master/conf/api.yml#L83-L101


Now ... I actually ran into exactly this issue at a client just recently... They had a recent code change in their AEM Component which forces AEM to response to **all** http request with a response code of `200` ... even errors were responded with 200 ...

**Comment by henrykuijpers** [comment] 2020-04-24 07:27
I think this was an issue in our setup, where we were executing these calls in the wrong place during the configuration part. We don't have this issue anymore. :)

**Comment by mbloch1986** [comment] 2020-04-25 06:53
@henrykuijpers  thanks for the update. I'll close that ticket.

**Closed by mbloch1986** 2020-04-25 06:53 UTC
